# Generated by Django 5.1.4 on 2025-11-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
    ]
