# Generated by Django 5.1.4 on 2025-10-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default='Changeme@123', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='Changeme@123', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='Changeme@123', max_length=100),
        ),
    ]
